name: RollerBlades
main: com.creeperevents.oggehej.rollerblades.RollerBlades
version: 1.0
description: Roll like a baws
author: oggehej
softdepend: [WorldGuard]
commands:
  RollerBlades:
    description: RollerBlades main command
    usage: /<command> [args]
    aliases: ro
permissions:
  rollerblades.use:
    description: Allow player to roll
    default: true
  rollerblades.reload:
    description: Allow player to reload the configuration
    default: op
